let canvas = document.getElementById("canvas");
let pen = canvas.getContext("2d");
let global_rows = 100;
let global_cols = 300;
canvas.style.top = "50px";
canvas.style.left = "50px";
let target_col = 0;
let target_row = 0;
let delay = 10;
let pixel_height = canvas.height / global_rows;
let pixel_width = canvas.width / global_cols;
let neighbors = 5;
let span = Math.floor(neighbors / 2);
let cells = new Array(global_rows * global_cols).fill(0);
let states = 2;
let filter_length = Math.pow(states, neighbors);
let filter = new Array(filter_length).fill(0);
let color = ["#000000", "#FFFFFF"];
//# sourceMappingURL=global.js.map